const amenities = [
    'Wifi',
    'Parking',
    'Gym',
    'Pool',
    'Cafe',
    'Restaurant',
    'Laundry',
    'AC',
    'Heater',
    'TV',
    'Fridge',
    'Microwave',
    'Washing Machine',
    'Dishwasher',
    'Oven',
    'Balcony',
    'Garden',
    'Terrace',
    'Lift',
    'Wheelchair Accessible',
    'Pet Friendly',
    'Smoke Friendly',
    'Events Friendly',
    'Kids Friendly',
    'Couples Friendly',
    'Family Friendly',
    'Bachelor Friendly',
];


module.exports = {amenities};
